### ISSUE TITLE
Tugas 2 Updating File

### ISSUE THREAD

**Issue by kurniaeliazar** [kurniaeliazar/Algorithm-II#2]

**Comment by exralvio** [comment]
Nama: Rizky Alvio Leegia
NPM: 06106103043
https://github.com/exralvio/Algorithm-II/tree/master/Tugas-2

**Comment by hafidzniioman** [comment]
Nama : Hafidz FIrdaus
NPM : 0616103047
https://github.com/hafidzniioman/updatingfiles

**Comment by iqbalilmanfirdaus** [comment]
Nama: Iqbal Ilman Firdaus
NMP: 0616103032
https://github.com/iqbalilmanfirdaus/Algoritma-Pemograman-2

**Comment by alifajri96** [comment]
Nama : Ali Fajri
NPM   : 0616103038
https://github.com/alifajri96/Algoritma-II/blob/master/Tugas-2-Updating/Update.cpp

**Comment by shin95** [comment]
Sindi Ibrahim Hidayattulloh
0616103028
https://github.com/shin95/Alpro-II/blob/master/Tugas_update/update.cpp

**Comment by rairaksa** [comment]
Rai Raksa M
061303011
https://github.com/raydeon7/Edu/tree/master/AP2/V%20-%20Update%20File

**Comment by nikoparulian** [comment]
Niko Parulian
061303036
https://github.com/nikoparulian/Updatingfile

**Comment by Bagusreza** [comment]
m bagus reza fahlevy
0616103042
https://github.com/Bagusreza/algoritmaII/blob/master/updating.cpp

**Comment by rikipermana25** [comment]
Riki Permana
0616103034
https://github.com/rikipermana25/ALGORITMA-II/tree/master/SOAL%20TUGAS%202
