### ISSUE TITLE
Quiz 1

### ISSUE THREAD

**Issue by kurniaeliazar** [kurniaeliazar/Algorithm-II#5]
Soal Quiz 1

Input format: (50)
Baris pertama berisi integer N 
Baris selanjutnya berisi B ke-1 s/d B ke-N

Output format: 
Bilangan O ke 1 s/d O ke N
O didapat dengan algoritma sbb : (Iterative 20, recursive 30)
jika O bilangan ganjil maka jumlah kan semua bilangan ganjil yg dimiliki dari 0 hingga O ganjil,
simpan bilangan B dan O ke file ganjil.txt 

jika O bilangan genap maka jumlah kan semua bilangan genap yg dimiliki dari 0 hingga O genap,
simpan bilangan B dan O ke file genap.txt

simpan ke file (20)

Contoh input          
2                               
9
6

Ganjil.txt 
9        25

Genap.txt
6          12

25 = 9 + 7 + 5 + 3 + 1
12 = 6 + 4 + 2

**Comment by jibrilrian** [comment]
Rian Mochamad Jibril
0616103039

**Comment by ridwanue** [comment]
Hadir

**Comment by shin95** [comment]
Sindi Ibrahim Hidayattulloh
0616103028

**Comment by iqbalilmanfirdaus** [comment]
iqbal ilman 
0616103032

**Comment by ridwanue** [comment]
Hadir Ridwan 0616103030

**Comment by AndryPangestu** [comment]
Andry Nugrohopangestu
0616103036

**Comment by kurniaeliazar** [comment]
test

**Comment by Hasbyzacky45** [comment]
Apip hasby jacky 0616103037

**Comment by Triadhy** [comment]
Muhammad Triadhy Purnomo 
0616103049

**Comment by yudicahyadi** [comment]
yudi cahyadi 0616103044

**Comment by Bagusreza** [comment]
muhammad bagus reza fahlevy
0616103042

**Comment by herman-f** [comment]
herman firansyah
0616103033

**Comment by dinanilham** [comment]
Dinan ilham
0616103041

**Comment by sadar123** [comment]
Sadar putra saleh daeli
0616103031

**Comment by exralvio** [comment]
Rizky Alvio Leegia
0616103043

**Comment by alifajri96** [comment]
Ali Fajri
0616103038

**Comment by rikipermana25** [comment]
Riki permana
0616103034

**Comment by rairaksa** [comment]
Rai Raksa M
061303011
https://github.com/raydeon7/Edu/tree/master/AP2/Quiz%201

**Comment by nikoparulian** [comment]
Niko Parulian
061303036
https://github.com/nikoparulian/Quiz1

**Comment by hafidzniioman** [comment]
hafidz firdaus
0616103047
